<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <!-- 4 layers: API → Application → Infrastructure → Domain -->
    <ProjectReference Include="..\IntegrationService.Application\IntegrationService.Application.csproj" />
    <ProjectReference Include="..\IntegrationService.Infrastructure\IntegrationService.Infrastructure.csproj" />
    <!-- Building blocks shared -->
    <ProjectReference Include="..\..\building-blocks\BuildingBlocks.Abstractions\BuildingBlocks.Abstractions.csproj" />
    <ProjectReference Include="..\..\building-blocks\BuildingBlocks.Core\BuildingBlocks.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="RabbitMQ.Client" Version="7.0.0" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.5.0" />
  </ItemGroup>

  <ItemGroup>
    <Content Update="configs\**\*.json" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

</Project>
